{{- if not .Values.opencti.adminTokenExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencti.fullname" . }}-credentials
  labels:
    {{- include "opencti.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ required "opencti.adminToken is required" .Values.opencti.adminToken | quote }}
  admin-password: {{ required "opencti.adminPassword is required" .Values.opencti.adminPassword | quote }}
  {{- if .Values.opencti.healthAccessKey }}
  health-access-key: {{ .Values.opencti.healthAccessKey | quote }}
  {{- end }}
{{- end }}
