{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencti.fullname" . }}-worker
  labels:
    {{- include "opencti.workerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount | default 3 }}
  {{- with .Values.worker.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opencti.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "opencti.workerEnv" . | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "opencti.workerSelectorLabels" . | nindent 8 }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opencti.serviceAccountName" . }}
      {{- with .Values.worker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.readyChecker.enabled }}
        {{- include "opencti.readyChecker" (dict "name" "server" "host" (printf "%s-server" (include "opencti.fullname" .)) "port" (.Values.server.service.port | default 80) "retries" .Values.readyChecker.retries "timeout" .Values.readyChecker.timeout "image" .Values.readyChecker.image) | nindent 8 }}
        {{- end }}
        {{- with .Values.worker.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: opencti-worker
          {{- with .Values.worker.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.worker.image.repository | default "opencti/worker" }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.worker.telemetry.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.worker.telemetry.port | default 14269 }}
              protocol: TCP
          {{- end }}
          env:
            {{- include "opencti.workerEnv" . | nindent 12 }}
            {{- with .Values.worker.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.worker.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
